ERROR - 2022-11-15 16:44:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\pemweb-restful-api\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\pemweb-restful-api\app\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(927): App\Controllers\Customers->index()
#8 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
#9 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pemweb-restful-api\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\pemweb-restful-api\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\pemweb-restful-api\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\pemweb-restful-api\app\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(927): App\Controllers\Customers->index()
#7 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
#8 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pemweb-restful-api\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pemweb-restful-api\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-11-15 16:44:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `customers`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Customers->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-15 16:44:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\pemweb-restful-api\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\pemweb-restful-api\app\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(927): App\Controllers\Customers->index()
#8 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
#9 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pemweb-restful-api\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\pemweb-restful-api\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\pemweb-restful-api\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\pemweb-restful-api\app\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(927): App\Controllers\Customers->index()
#7 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
#8 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pemweb-restful-api\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pemweb-restful-api\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-11-15 16:44:43 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `customers`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Customers->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-15 16:45:19 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', 'dbcustomer', 3306, '', 0)
#1 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\pemweb-restful-api\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\pemweb-restful-api\app\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(927): App\Controllers\Customers->index()
#8 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
#9 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pemweb-restful-api\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\pemweb-restful-api\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\pemweb-restful-api\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\pemweb-restful-api\app\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(927): App\Controllers\Customers->index()
#7 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
#8 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pemweb-restful-api\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pemweb-restful-api\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-11-15 16:45:19 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `customers`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Customers->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-15 16:48:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', 'dbcustomer', 3306, '', 0)
#1 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\pemweb-restful-api\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\pemweb-restful-api\app\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(927): App\Controllers\Customers->index()
#8 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
#9 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pemweb-restful-api\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\pemweb-restful-api\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\pemweb-restful-api\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\pemweb-restful-api\app\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(927): App\Controllers\Customers->index()
#7 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
#8 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pemweb-restful-api\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pemweb-restful-api\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-11-15 16:48:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `customers`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Customers->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-15 16:48:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', 'dbcustomer', 3306, '', 0)
#1 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cu...', Array, false)
#4 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\pemweb-restful-api\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\pemweb-restful-api\app\Controllers\Customers.php(53): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(927): App\Controllers\Customers->create()
#9 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
#10 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\pemweb-restful-api\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\pemweb-restful-api\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cu...', Array, false)
#3 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\pemweb-restful-api\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\pemweb-restful-api\app\Controllers\Customers.php(53): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(927): App\Controllers\Customers->create()
#8 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
#9 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pemweb-restful-api\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\pemweb-restful-api\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-11-15 16:48:07 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `customers` (`first_name`, `last_name`) VALUES (:first_name:, :last_name:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Customers.php(53): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Customers->create()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-15 16:51:45 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'competitiondb' in C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'competitionDB', 3306, '', 0)
#1 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\pemweb-restful-api\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\pemweb-restful-api\app\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(927): App\Controllers\Customers->index()
#8 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
#9 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pemweb-restful-api\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\pemweb-restful-api\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'competitiondb' in C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\pemweb-restful-api\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\pemweb-restful-api\app\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(927): App\Controllers\Customers->index()
#7 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
#8 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pemweb-restful-api\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\pemweb-restful-api\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-11-15 16:51:45 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'competitiondb'
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `customers`', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Customers->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-15 17:01:41 --> mysqli_sql_exception: Table 'competitiondb.customers' doesn't exist in C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\pemweb-restful-api\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\pemweb-restful-api\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\pemweb-restful-api\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\pemweb-restful-api\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\pemweb-restful-api\app\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(927): App\Controllers\Customers->index()
#8 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
#9 C:\xampp\htdocs\pemweb-restful-api\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pemweb-restful-api\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\pemweb-restful-api\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-11-15 17:01:41 --> Call to a member function getResult() on bool
in SYSTEMPATH\Model.php on line 224.
 1 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 2 APPPATH\Controllers\Customers.php(32): CodeIgniter\BaseModel->findAll()
 3 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Customers->index()
 4 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
